### ISSUE TITLE
example php code on how to move subscribers to another list please

### ISSUE THREAD

**Issue by surfdemon** [aweber/AWeber-API-PHP-Library#10]
Please can you provide examples of how to move subscribers from one list to another there appears to be the option with a move method but no examples on how to use this method.

**Comment by CreativForm** [comment]
Can you pprovide info how todo that for one subscriber by email? Thanks!

**Comment by ToastedQuarks** [comment]
@jon9 , you can always get help with the AWeber API by writing an email to api@aweber.com. We're more likely to see your questions there.

If a subscriber is already on the destination list a 405 status code will be returned with the message "Subscriber already belongs to this list."

I'd recommend a simple try/catch block so you can catch the exception and then handle it as you like and just move on to the next thing. You could add in handling for all the errors that way too, and make your code less prone to crashing. 

Something like this should do it (example catch modified from the docs at [AWeber Labs](https://labs.aweber.com)):

```
catch(AWeberAPIException $exc) {
    print "<h3>AWeberAPIException:</h3>";
    print " <li> Type: $exc->type              <br>";
    print " <li> Status: $exc->status          <br>";
    print " <li> Msg : $exc->message           <br>";
    print " <li> Docs: $exc->documentation_url <br>";
    print "<hr>";

    // Put your error handling here, or replace the print lines above
}
```
