### ISSUE TITLE
API Causing issue when Inserting large number of subscribers from one list to another

### ISSUE THREAD

**Issue by gaurab** [aweber/AWeber-API-PHP-Library#20]
I have got certain requirement to add the existing subscribers from a list to another list , checking some conditions on the way.

But the script is executing too slow and most of the time it is showing " Uncaught exception 'AWeberAPIException' with message 'Rate limit exceeded (API requests per customer account per minute). ". and API connection is disconnected.

For this i also added sleep(10)  at the below of the loop to minimize this issue.
- I have twice used the "find" method to search for a subscriber in a list and added the subscriber to another list if the subscriber is not already existed in the current list.

Any suggestions regarding this.

**Comment by jon9** [comment]
Should the following code sleep time be set to 60 sec opposed to 5 sec?

<?php
132 $data = json_decode($response->body, true); 
133 while (( $response->headers['Status-Code'] == 403) && ($data['error']['type'] === 'RateLimitError')) {
134     sleep(5);
135     $response = $this->makeRequest($method, $url, $data);
135     $data = json_decode($response->body, true); 
136 }
?>
