### ISSUE TITLE
Consumer key is invalid only when trying to create a record

### ISSUE THREAD

**Issue by aprice42** [aweber/AWeber-API-PHP-Library#41]
Hello, 

I have gone through the example code for PHP on the Aweber api site, and I am successfully finding subscribers by email and getting list details by list name. However, I am getting an error when I try to add a subscriber.

when I call:
```
try {
$list->subscribers->create($subscriber);
}
```
I am getting the error: 
```
exception 'AWeberAPIException' with message 'Consumer key is invalid. https://labs.aweber.com/docs/troubleshooting#unauthorized' in /Users/andy/Sites/hiq.stage/sites/all/modules/custom/hiq_signup/aweber_api/oauth_application.php:484
```
Any idea why I am getting a consumer key is not valid error when trying to create data but not when trying to read? I have reviewed the support article referenced in the error however, it provides no insight into this issue particular issue. So, I am hopeful someone here might have an idea, or know if this is a bug? 

Thanks,
Andy

**Comment by amberheilman** [comment]
How are you creating/getting the $list object? Did you use this example add_subscriber method here: https://labs.aweber.com/getting_started/private#private_finished_app ?

You might be missing the consumer key & secret from the $account variable.

**Comment by aprice42** [comment]
Thank you for the quick reply. I am basically using all of the example methods that you linked to here: https://labs.aweber.com/getting_started/private#private_finished_app. 

And specifically this to get the list:

```
function findList($listName) {
        $account = $this->application->getAccount($this->accessToken, $this->accessSecret);
        print_r($account->lists);

        $foundLists = $account->lists->find(array('name' => $listName));
        //must pass an associative array to the find method

        print_r($foundLists);

        return $foundLists[0];
    }
```
That method is returning information that I would expect when called by itself. But, are you saying that I need to include the consumer key and secret somehow that is not shown in that example when creating an entry? Aren't they included as part of the $this->application object? 

```
function __construct() {
        # replace XXX with your real keys and secrets
        $this->consumerKey = 'XXX';
        $this->consumerSecret = 'XXX';
        $this->accessToken = 'XXX';
        $this->accessSecret = 'XXX';

        $this->application = new AWeberAPI($this->consumerKey, $this->consumerSecret);
    }

```
Sorry if this is a dumb question, I am a bit of an OOP noob. :)

Thanks, 
Andy

**Comment by amberheilman** [comment]
It looks like what you are doing is correct from what I can tell. Double check if your consumer key or secret contains any spaces, or if they are the exact copy of what is displayed here: https://labs.aweber.com/apps. If this does not solve it, we will need a bit more information.

In order for us to do a bit more digging, could you please create a support ticket by going to https://labs.aweber.com and clicking on "Support" in the upper right hand corner.

Include the following:
-Consumer key
-Consumer Secret
-App ID
-Account id (for the AWeber account you are accessing)
-Access Token (for the AWeber account you are accessing)
-Access Secret (for the AWeber account you are accessing)
-The complete code you are using (you can include just this if it contains all the prior information)

Mention me in the support ticket, and I will check this out.

Thanks,
Amber

**Comment by aprice42** [comment]
Hi Amber, thank you for your replies. As I went to create the ticket, I decided to try a test once more, and it worked. I made no changes to my code whatsoever, any thoughts why it might not have worked to begin with? Could an error like this be triggered if the api service is unavailable or there is some server related issue? Or would that cause a different error?

Thank you again for your time.

**Comment by amberheilman** [comment]
I have not encountered anything quite like that. There has also been no downtime to explain the issue. Please let us know if this happens again, maybe we can distinguish a pattern.
Thanks!

**Comment by gitspider** [comment]
This error happens to me, too. I can get even list collection and an individual list, but when trying to get subscribers, got error "Invalid consumer key or access token key". 
Please help me. Thanks

**Comment by nvllsvm** [comment]
@gitspider This is not an issue with the library. Contact api@aweber.com and they will help you resolve it.
