### ISSUE TITLE
Doesn't work with cronjob

### ISSUE THREAD

**Issue by behnampmdg3** [aweber/AWeber-API-PHP-Library#46]
Hello;

Aweber is blocking my cron jobs! I can run the script directly and add users to list, but using cron job it doesnt allow me. 

There are no code samples like this in docs. How can we fix this?

<?php 

if(count($result)>0)
    {
        ##Add aweber
        require_once('aweber/aweber_api/aweber_api.php');
        $consumerKey = '';
        $consumerSecret = '';
        $accessKey      = '**_'; # put your credentials here
        $accessSecret   = '**_'; # put your credentials here
        $account_id     = '***'; # put the Account ID here
        $list_id        = ''; # put the List ID here  
        $aweber = new AWeberAPI($consumerKey, $consumerSecret);
        # Get an access token
        if(empty($_COOKIE['accessToken']))
            {
                if (empty($_GET['oauth_token'])) 
                    {
                        $callbackUrl = 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
                        list($requestToken, $requestTokenSecret) = $aweber->getRequestToken($callbackUrl);
                        setcookie('requestTokenSecret', $requestTokenSecret);
                        setcookie('callbackUrl', $callbackUrl);
                        header("Location: {$aweber->getAuthorizeUrl()}");
                        exit();
                    }
                $aweber->user->tokenSecret = $_COOKIE['requestTokenSecret'];
                $aweber->user->requestToken = $_GET['oauth_token'];
                $aweber->user->verifier = $_GET['oauth_verifier'];
                list($accessToken, $accessTokenSecret) = $aweber->getAccessToken();
                setcookie('accessToken', $accessToken);
                setcookie('accessTokenSecret', $accessTokenSecret);
                header('Location: '.$_COOKIE['callbackUrl']);
                exit();
            }
        ##End add aweber

```
    foreach($result as $val=>$row)
        {
            # Get AWeber Account
                try {
                        $account = $aweber->getAccount($_COOKIE['accessToken'], $_COOKIE['accessTokenSecret']);
                        $listURL = "https://api.aweber.com/1.0/accounts/***/lists/".$list_id;
                        $list = $account->loadFromUrl($listURL);
                        $params = array(
                            'email' => $row->email
                        );
                        $subscribers = $list->subscribers;
                         # success!
                        //print "A new subscriber was added to the $list->name list!";
                    }
                catch(AWeberAPIException $exc) 
                    {
                        print "<h3>AWeberAPIException:</h3>";
                        print " <li> Type: $exc->type              <br>";
                        print " <li> Msg : $exc->message           <br>";
                        print " <li> Docs: $exc->documentation_url <br>";
                        print "<hr>";
                        //exit(1);
                    }
        }
}
```

**Comment by CodeDestroyer** [comment]
@behnampmdg3 a cron job is not going to have all the http access like $_GET, $_Cookie
here is a command line example

```
$application = new AWeberAPI($consumerKey, $consumerSecret);
# get a request token using oob as the callback URL
list($requestToken, $tokenSecret) = $application->getRequestToken('oob');
# prompt user to go to authorization URL
echo "Go to this url in your browser: {$application->getAuthorizeUrl()}\n";
# get the verifier code
echo 'Type code here: ';
$code = trim(fgets(STDIN));
# turn on debug mode for more information
$application->adapter->debug = true;
# exchange request token + verifier code for an access token
$application->user->requestToken = $requestToken;
$application->user->tokenSecret = $tokenSecret;
$application->user->verifier = $code;
list($accessToken, $accessSecret) = $application->getAccessToken();
# show your access token
print "\n$accessToken\n$accessSecret\n";
```

if you already have the `$accessToken` and `$accessSecret ` value you do not need to run getAccessToken again, you can store those two values somewhere, they are good unless revoked.
