### ISSUE TITLE
Class 'AWeberAPI' not found

### ISSUE THREAD

**Issue by amlbar** [aweber/AWeber-API-PHP-Library#54]
Hi can you help me with this? I'm using php composer. 

php code: 

``` php
require('vendor/autoload.php');
new PHPExcel;
new AWeberAPI;
```

composer.json

``` json
{
    "require": {
        "aweber/aweber": "^1.1",
        "phpoffice/phpexcel": "^1.8"
    }
}
```

**Comment by robbieaverill** [comment]
As [noted on Stackoverflow](http://stackoverflow.com/a/39156398/2812842) this would probably be a breaking change to allow it to work with composer correctly.

One alternative would be to implement the file e.g. `AWeberAPI.php` which required `aweber_api.php` - this wouldn't be a breaking change.

**Comment by florianlenz** [comment]
I really prefer this fork which contains a nice and simple fix. It would be nice if someone merge @robbieaverill's branch in a new version. This "bug" is really annoying and here #48 is a solution that is working and this is open for 10 Months.

**Comment by nvllsvm** [comment]
Version 1.1.16 has been released and resolves Composer autoloading.
