### ISSUE TITLE
Detect offset in local machine time vs UTC

### ISSUE THREAD

**Issue by jibbius** [aweber/AWeber-API-PHP-Library#57]
I'm running code on a server, where the system clock has not been setup correctly (it's off by roughly 1 hour).
Even though the clock is wrong, I don't have permissions to change the system clock.

The problem this creates is when the Aweber API library attempts to create a nonce for the initial oauth handshake:

    /* oauth_application.php */
    public function generateNonce($timestamp = false) {
        if (!$timestamp) $timestamp = $this->generateTimestamp();
        return md5($timestamp.'-'.rand(10000,99999).'-'.uniqid());
    }

    public function generateTimestamp() {
        return time();
    }

This results in a stale timestamp being created on the local machine.

When attempting to retrieve a token with the stale timestamp, this later result in:

    exception 'AWeberAPIException' with message 'Expired timestamp: given 1478182114 and now 1478182622 has a greater difference than threshold 300

It would be really great if the default implementation of **generateTimestamp()** was able to cater for this use case.

**Comment by nvllsvm** [comment]
The PHP time() function returns UNIX time which is always UTC. 

Ultimately, you'll have to change to change the system clock.

**Comment by jibbius** [comment]
Thanks for the response.
Yes - I understand that is how PHP time() works.

The fix for me will probably just be to hardcode an offset (turns out it's only 8mins), as the server is shared with other sites; a request to change the time on it will not be worth the effort.

Flagged this as an issue, because I don't know how many users will be in this situation ( I suspect it does come up occasionally ). Anyhow, I can understand the decision to leave this as a "won't fix".
