### ISSUE TITLE
real php examples please

### ISSUE THREAD

**Issue by commentluv** [aweber/AWeber-API-PHP-Library#8]
ok so I've gone through the demo and see how that works but it's only getting an account and then parsing items in the account object.
I need to see real code examples for more advanced things.

I know that I can get the account (after authorizing) with

$aweber = new AWeberAPI($data['consumerKey'], $data['consumerSecret']);
$account = $aweber->getAccount($_COOKIE['accessToken'], $_COOKIE['accessTokenSecret']);

and I figured out how to get the account id and iterate through the lists to get the list id and with that search for an email address with this

$object = $aweber->loadFromUrl('https://api.aweber.com/1.0/accounts/'.$id.'/lists/'.$list->id.'/subscribers?ws.op=find&email='.$email);

that gives me an object with an array of data, I know there is a 'self_link' in there and can use it to return the user object but what is the proper way to retrieve 'self_link' from $object above?

I need more practical examples, once I see a few then I am good to go on. how about something more advanced like moving a subscriber or deleting them? how to implement POST vars

**Comment by tariqwebstar** [comment]
How to create broadcast using API via PHP ?
